# Generated by Django 4.1.4 on 2023-01-06 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='email',
            new_name='username',
        ),
    ]
